name: Weaver-soft
favicon: null
layout_spectrum: 0.8717110452707857
typography_spectrum: 0.6823843475431204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.24573546997271478
  lightness: 0.36958969244733453
  saturation: 0.4610454870853573
  rhythmicContrast: 0.7657530896831304
purpose: []
